/*Constants: Application Enumerations.*/

package constants

var Statuses = struct {
	NEW      Status
	ACTIVE   Status
	INACTIVE Status
	DISABLED Status
	DELETED  Status
}{
	NEW: NEW,
	// ACTIVE:   ACTIVE,
	INACTIVE: INACTIVE,
	DISABLED: DISABLED,
	DELETED:  DELETED,
}

var Roles = struct {
	ADMIN     Role
	USER      Role
	DEVELOPER Role
}{
	ADMIN:     ADMIN,
	USER:      USER,
	DEVELOPER: DEVELOPER,
}

var CardTypes = struct {
	CHEQUE  CardType
	SAVINGS CardType
	CREDIT  CardType
}{
	CHEQUE:  CHEQUE,
	SAVINGS: SAVINGS,
	CREDIT:  CREDIT,
}

var Verifications = struct {
	UNVERIFIED Verification
	VERIFIED   Verification
	VERIFYING  Verification
	FAILED     Verification
	EXPIRED    Verification
}{
	UNVERIFIED: UNVERIFIED,
	VERIFIED:   VERIFIED,
	VERIFYING:  VERIFYING,
	FAILED:     FAILED,
	EXPIRED:    EXPIRED,
}

var Communications = struct {
	EMAIL Communication
	SMS   Communication
	CELL  Communication
	SLACK Communication
}{
	EMAIL: COMMUNICATIONEMAIL,
	SMS:   SMS,
	CELL:  CELL,
	SLACK: COMMUNICATIONSLACK,
}

var DevicePermissions = struct {
	CAMERA   DevicePermission
	STORAGE  DevicePermission
	CONTACTS DevicePermission
}{
	CAMERA:   CAMERA,
	STORAGE:  STORAGE,
	CONTACTS: CONTACTS,
}

var LoginMethods = struct {
	EMAIL    LoginMethod
	GITHUB   LoginMethod
	SLACK    LoginMethod
	GOOGLE   LoginMethod
	FACEBOOK LoginMethod
}{
	EMAIL:    LOGINEMAIL,
	GITHUB:   GITHUB,
	SLACK:    LOGINSLACK,
	GOOGLE:   GOOGLE,
	FACEBOOK: FACEBOOK,
}

var DataSharingPreferences = struct {
	ACCOUNT      DataSharingPreference
	PROFILE      DataSharingPreference
	SETTINGS     DataSharingPreference
	TRANSACTIONS DataSharingPreference
}{
	ACCOUNT:      ACCOUNT,
	PROFILE:      PROFILE,
	SETTINGS:     SETTINGS,
	TRANSACTIONS: TRANSACTIONS,
}

var ProfileVisibilities = struct {
	PRIVATE ProfileVisibility
	PUBLIC  ProfileVisibility
	ADMIN   ProfileVisibility
}{
	PRIVATE: PRIVATE,
	PUBLIC:  PUBLIC,
	ADMIN:   PROFILEVISIBILITYADMIN,
}

var Themes = struct {
	SYSTEM Theme
	DARK   Theme
	LIGHT  Theme
	RED    Theme
	GREEN  Theme
	BLUE   Theme
}{
	SYSTEM: SYSTEM,
	DARK:   DARK,
	LIGHT:  LIGHT,
	RED:    RED,
	GREEN:  GREEN,
	BLUE:   BLUE,
}

var Countries = struct {
	AFGHANISTAN                  Country
	ALBANIA                      Country
	ALGERIA                      Country
	ANDORRA                      Country
	ANGOLA                       Country
	ANTIGUA_AND_BARBUDA          Country
	ARGENTINA                    Country
	ARMENIA                      Country
	AUSTRALIA                    Country
	AUSTRIA                      Country
	AZERBAIJAN                   Country
	BAHAMAS                      Country
	BAHRAIN                      Country
	BANGLADESH                   Country
	BARBADOS                     Country
	BELARUS                      Country
	BELGIUM                      Country
	BELIZE                       Country
	BENIN                        Country
	BHUTAN                       Country
	BOLIVIA                      Country
	BOSNIA_AND_HERZEGOVINA       Country
	BOTSWANA                     Country
	BRAZIL                       Country
	BRUNEI                       Country
	BULGARIA                     Country
	BURKINA_FASO                 Country
	BURUNDI                      Country
	CABO_VERDE                   Country
	CAMBODIA                     Country
	CAMEROON                     Country
	CANADA                       Country
	CENTRAL_AFRICAN_REPUBLIC     Country
	CHAD                         Country
	CHILE                        Country
	CHINA                        Country
	COLOMBIA                     Country
	COMOROS                      Country
	CONGO_DEMOCRATIC_REPUBLIC    Country
	CONGO_REPUBLIC               Country
	COSTA_RICA                   Country
	COTE_DIVOIRE                 Country
	CROATIA                      Country
	CUBA                         Country
	CYPRUS                       Country
	CZECH_REPUBLIC               Country
	DENMARK                      Country
	DJIBOUTI                     Country
	DOMINICA                     Country
	DOMINICAN_REPUBLIC           Country
	ECUADOR                      Country
	EGYPT                        Country
	EL_SALVADOR                  Country
	EQUATORIAL_GUINEA            Country
	ERITREA                      Country
	ESTONIA                      Country
	ESWATINI                     Country
	ETHIOPIA                     Country
	FIJI                         Country
	FINLAND                      Country
	FRANCE                       Country
	GABON                        Country
	GAMBIA                       Country
	GEORGIA                      Country
	GERMANY                      Country
	GHANA                        Country
	GREECE                       Country
	GRENADA                      Country
	GUATEMALA                    Country
	GUINEA                       Country
	GUINEA_BISSAU                Country
	GUYANA                       Country
	HAITI                        Country
	HONDURAS                     Country
	HUNGARY                      Country
	ICELAND                      Country
	INDIA                        Country
	INDONESIA                    Country
	IRAN                         Country
	IRAQ                         Country
	IRELAND                      Country
	ISRAEL                       Country
	ITALY                        Country
	JAMAICA                      Country
	JAPAN                        Country
	JORDAN                       Country
	KAZAKHSTAN                   Country
	KENYA                        Country
	KIRIBATI                     Country
	KOREA_NORTH                  Country
	KOREA_SOUTH                  Country
	KOSOVO                       Country
	KUWAIT                       Country
	KYRGYZSTAN                   Country
	LAOS                         Country
	LATVIA                       Country
	LEBANON                      Country
	LESOTHO                      Country
	LIBERIA                      Country
	LIBYA                        Country
	LIECHTENSTEIN                Country
	LITHUANIA                    Country
	LUXEMBOURG                   Country
	MADAGASCAR                   Country
	MALAWI                       Country
	MALAYSIA                     Country
	MALDIVES                     Country
	MALI                         Country
	MALTA                        Country
	MARSHALL_ISLANDS             Country
	MAURITANIA                   Country
	MAURITIUS                    Country
	MEXICO                       Country
	MICRONESIA                   Country
	MOLDOVA                      Country
	MONACO                       Country
	MONGOLIA                     Country
	MONTENEGRO                   Country
	MOROCCO                      Country
	MOZAMBIQUE                   Country
	MYANMAR                      Country
	NAMIBIA                      Country
	NAURU                        Country
	NEPAL                        Country
	NETHERLANDS                  Country
	NEW_ZEALAND                  Country
	NICARAGUA                    Country
	NIGER                        Country
	NIGERIA                      Country
	NORTH_MACEDONIA              Country
	NORWAY                       Country
	OMAN                         Country
	PAKISTAN                     Country
	PALAU                        Country
	PALESTINE                    Country
	PANAMA                       Country
	PAPUA_NEW_GUINEA             Country
	PARAGUAY                     Country
	PERU                         Country
	PHILIPPINES                  Country
	POLAND                       Country
	PORTUGAL                     Country
	QATAR                        Country
	ROMANIA                      Country
	RUSSIA                       Country
	RWANDA                       Country
	SAINT_KITTS_AND_NEVIS        Country
	SAINT_LUCIA                  Country
	SAINT_VINCENT_AND_GRENADINES Country
	SAMOA                        Country
	SAN_MARINO                   Country
	SAO_TOME_AND_PRINCIPE        Country
	SAUDI_ARABIA                 Country
	SENEGAL                      Country
	SERBIA                       Country
	SEYCHELLES                   Country
	SIERRA_LEONE                 Country
	SINGAPORE                    Country
	SLOVAKIA                     Country
	SLOVENIA                     Country
	SOLOMON_ISLANDS              Country
	SOMALIA                      Country
	SOUTH_AFRICA                 Country
	SOUTH_SUDAN                  Country
	SPAIN                        Country
	SRI_LANKA                    Country
	SUDAN                        Country
	SURINAME                     Country
	SWEDEN                       Country
	SWITZERLAND                  Country
	SYRIA                        Country
	TAIWAN                       Country
	TAJIKISTAN                   Country
	TANZANIA                     Country
	THAILAND                     Country
	TIMOR_LESTE                  Country
	TOGO                         Country
	TONGA                        Country
	TRINIDAD_AND_TOBAGO          Country
	TUNISIA                      Country
	TURKEY                       Country
	TURKMENISTAN                 Country
	TUVALU                       Country
	UGANDA                       Country
	UKRAINE                      Country
	UNITED_ARAB_EMIRATES         Country
	UNITED_KINGDOM               Country
	UNITED_STATES                Country
	URUGUAY                      Country
	UZBEKISTAN                   Country
	VANUATU                      Country
	VATICAN_CITY                 Country
	VENEZUELA                    Country
	VIETNAM                      Country
	YEMEN                        Country
	ZAMBIA                       Country
	ZIMBABWE                     Country
}{
	AFGHANISTAN:                  AFGHANISTAN,
	ALBANIA:                      ALBANIA,
	ALGERIA:                      ALGERIA,
	ANDORRA:                      ANDORRA,
	ANGOLA:                       ANGOLA,
	ANTIGUA_AND_BARBUDA:          ANTIGUA_AND_BARBUDA,
	ARGENTINA:                    ARGENTINA,
	ARMENIA:                      ARMENIA,
	AUSTRALIA:                    AUSTRALIA,
	AUSTRIA:                      AUSTRIA,
	AZERBAIJAN:                   AZERBAIJAN,
	BAHAMAS:                      BAHAMAS,
	BAHRAIN:                      BAHRAIN,
	BANGLADESH:                   BANGLADESH,
	BARBADOS:                     BARBADOS,
	BELARUS:                      BELARUS,
	BELGIUM:                      BELGIUM,
	BELIZE:                       BELIZE,
	BENIN:                        BENIN,
	BHUTAN:                       BHUTAN,
	BOLIVIA:                      BOLIVIA,
	BOSNIA_AND_HERZEGOVINA:       BOSNIA_AND_HERZEGOVINA,
	BOTSWANA:                     BOTSWANA,
	BRAZIL:                       BRAZIL,
	BRUNEI:                       BRUNEI,
	BULGARIA:                     BULGARIA,
	BURKINA_FASO:                 BURKINA_FASO,
	BURUNDI:                      BURUNDI,
	CABO_VERDE:                   CABO_VERDE,
	CAMBODIA:                     CAMBODIA,
	CAMEROON:                     CAMEROON,
	CANADA:                       CANADA,
	CENTRAL_AFRICAN_REPUBLIC:     CENTRAL_AFRICAN_REPUBLIC,
	CHAD:                         CHAD,
	CHILE:                        CHILE,
	CHINA:                        CHINA,
	COLOMBIA:                     COLOMBIA,
	COMOROS:                      COMOROS,
	CONGO_DEMOCRATIC_REPUBLIC:    CONGO_DEMOCRATIC_REPUBLIC,
	CONGO_REPUBLIC:               CONGO_REPUBLIC,
	COSTA_RICA:                   COSTA_RICA,
	COTE_DIVOIRE:                 COTE_DIVOIRE,
	CROATIA:                      CROATIA,
	CUBA:                         CUBA,
	CYPRUS:                       CYPRUS,
	CZECH_REPUBLIC:               CZECH_REPUBLIC,
	DENMARK:                      DENMARK,
	DJIBOUTI:                     DJIBOUTI,
	DOMINICA:                     DOMINICA,
	DOMINICAN_REPUBLIC:           DOMINICAN_REPUBLIC,
	ECUADOR:                      ECUADOR,
	EGYPT:                        EGYPT,
	EL_SALVADOR:                  EL_SALVADOR,
	EQUATORIAL_GUINEA:            EQUATORIAL_GUINEA,
	ERITREA:                      ERITREA,
	ESTONIA:                      ESTONIA,
	ESWATINI:                     ESWATINI,
	ETHIOPIA:                     ETHIOPIA,
	FIJI:                         FIJI,
	FINLAND:                      FINLAND,
	FRANCE:                       FRANCE,
	GABON:                        GABON,
	GAMBIA:                       GAMBIA,
	GEORGIA:                      GEORGIA,
	GERMANY:                      GERMANY,
	GHANA:                        GHANA,
	GREECE:                       GREECE,
	GRENADA:                      GRENADA,
	GUATEMALA:                    GUATEMALA,
	GUINEA:                       GUINEA,
	GUINEA_BISSAU:                GUINEA_BISSAU,
	GUYANA:                       GUYANA,
	HAITI:                        HAITI,
	HONDURAS:                     HONDURAS,
	HUNGARY:                      HUNGARY,
	ICELAND:                      ICELAND,
	INDIA:                        INDIA,
	INDONESIA:                    INDONESIA,
	IRAN:                         IRAN,
	IRAQ:                         IRAQ,
	IRELAND:                      IRELAND,
	ISRAEL:                       ISRAEL,
	ITALY:                        ITALY,
	JAMAICA:                      JAMAICA,
	JAPAN:                        JAPAN,
	JORDAN:                       JORDAN,
	KAZAKHSTAN:                   KAZAKHSTAN,
	KENYA:                        KENYA,
	KIRIBATI:                     KIRIBATI,
	KOREA_NORTH:                  KOREA_NORTH,
	KOREA_SOUTH:                  KOREA_SOUTH,
	KOSOVO:                       KOSOVO,
	KUWAIT:                       KUWAIT,
	KYRGYZSTAN:                   KYRGYZSTAN,
	LAOS:                         LAOS,
	LATVIA:                       LATVIA,
	LEBANON:                      LEBANON,
	LESOTHO:                      LESOTHO,
	LIBERIA:                      LIBERIA,
	LIBYA:                        LIBYA,
	LIECHTENSTEIN:                LIECHTENSTEIN,
	LITHUANIA:                    LITHUANIA,
	LUXEMBOURG:                   LUXEMBOURG,
	MADAGASCAR:                   MADAGASCAR,
	MALAWI:                       MALAWI,
	MALAYSIA:                     MALAYSIA,
	MALDIVES:                     MALDIVES,
	MALI:                         MALI,
	MALTA:                        MALTA,
	MARSHALL_ISLANDS:             MARSHALL_ISLANDS,
	MAURITANIA:                   MAURITANIA,
	MAURITIUS:                    MAURITIUS,
	MEXICO:                       MEXICO,
	MICRONESIA:                   MICRONESIA,
	MOLDOVA:                      MOLDOVA,
	MONACO:                       MONACO,
	MONGOLIA:                     MONGOLIA,
	MONTENEGRO:                   MONTENEGRO,
	MOROCCO:                      MOROCCO,
	MOZAMBIQUE:                   MOZAMBIQUE,
	MYANMAR:                      MYANMAR,
	NAMIBIA:                      NAMIBIA,
	NAURU:                        NAURU,
	NEPAL:                        NEPAL,
	NETHERLANDS:                  NETHERLANDS,
	NEW_ZEALAND:                  NEW_ZEALAND,
	NICARAGUA:                    NICARAGUA,
	NIGER:                        NIGER,
	NIGERIA:                      NIGERIA,
	NORTH_MACEDONIA:              NORTH_MACEDONIA,
	NORWAY:                       NORWAY,
	OMAN:                         OMAN,
	PAKISTAN:                     PAKISTAN,
	PALAU:                        PALAU,
	PALESTINE:                    PALESTINE,
	PANAMA:                       PANAMA,
	PAPUA_NEW_GUINEA:             PAPUA_NEW_GUINEA,
	PARAGUAY:                     PARAGUAY,
	PERU:                         PERU,
	PHILIPPINES:                  PHILIPPINES,
	POLAND:                       POLAND,
	PORTUGAL:                     PORTUGAL,
	QATAR:                        QATAR,
	ROMANIA:                      ROMANIA,
	RUSSIA:                       RUSSIA,
	RWANDA:                       RWANDA,
	SAINT_KITTS_AND_NEVIS:        SAINT_KITTS_AND_NEVIS,
	SAINT_LUCIA:                  SAINT_LUCIA,
	SAINT_VINCENT_AND_GRENADINES: SAINT_VINCENT_AND_GRENADINES,
	SAMOA:                        SAMOA,
	SAN_MARINO:                   SAN_MARINO,
	SAO_TOME_AND_PRINCIPE:        SAO_TOME_AND_PRINCIPE,
	SAUDI_ARABIA:                 SAUDI_ARABIA,
	SENEGAL:                      SENEGAL,
	SERBIA:                       SERBIA,
	SEYCHELLES:                   SEYCHELLES,
	SIERRA_LEONE:                 SIERRA_LEONE,
	SINGAPORE:                    SINGAPORE,
	SLOVAKIA:                     SLOVAKIA,
	SLOVENIA:                     SLOVENIA,
	SOLOMON_ISLANDS:              SOLOMON_ISLANDS,
	SOMALIA:                      SOMALIA,
	SOUTH_AFRICA:                 SOUTH_AFRICA,
	SOUTH_SUDAN:                  SOUTH_SUDAN,
	SPAIN:                        SPAIN,
	SRI_LANKA:                    SRI_LANKA,
	SUDAN:                        SUDAN,
	SURINAME:                     SURINAME,
	SWEDEN:                       SWEDEN,
	SWITZERLAND:                  SWITZERLAND,
	SYRIA:                        SYRIA,
	TAIWAN:                       TAIWAN,
	TAJIKISTAN:                   TAJIKISTAN,
	TANZANIA:                     TANZANIA,
	THAILAND:                     THAILAND,
	TIMOR_LESTE:                  TIMOR_LESTE,
	TOGO:                         TOGO,
	TONGA:                        TONGA,
	TRINIDAD_AND_TOBAGO:          TRINIDAD_AND_TOBAGO,
	TUNISIA:                      TUNISIA,
	TURKEY:                       TURKEY,
	TURKMENISTAN:                 TURKMENISTAN,
	TUVALU:                       TUVALU,
	UGANDA:                       UGANDA,
	UKRAINE:                      UKRAINE,
	UNITED_ARAB_EMIRATES:         UNITED_ARAB_EMIRATES,
	UNITED_KINGDOM:               UNITED_KINGDOM,
	UNITED_STATES:                UNITED_STATES,
	URUGUAY:                      URUGUAY,
	UZBEKISTAN:                   UZBEKISTAN,
	VANUATU:                      VANUATU,
	VATICAN_CITY:                 VATICAN_CITY,
	VENEZUELA:                    VENEZUELA,
	VIETNAM:                      VIETNAM,
	YEMEN:                        YEMEN,
	ZAMBIA:                       ZAMBIA,
	ZIMBABWE:                     ZIMBABWE,
}

var Genders = struct {
	MALE         Gender
	FEMALE       Gender
	OTHER_GENDER Gender
}{
	MALE:         MALE,
	FEMALE:       FEMALE,
	OTHER_GENDER: OTHER_GENDER,
}

var Languages = struct {
	AFRIKAANS        Language
	ALBANIAN         Language
	AMHARIC          Language
	ARABIC           Language
	ARMENIAN         Language
	ASSAMESE         Language
	AZERBAIJANI      Language
	BENGALI          Language
	BOSNIAN          Language
	BULGARIAN        Language
	BURMESE          Language
	CATALAN          Language
	CHINESE_MANDARIN Language
	CROATIAN         Language
	CZECH            Language
	DANISH           Language
	DUTCH            Language
	ENGLISH          Language
	ESTONIAN         Language
	FINNISH          Language
	FRENCH           Language
	GEORGIAN         Language
	GERMAN           Language
	GREEK            Language
	GUJARATI         Language
	HEBREW           Language
	HINDI            Language
	HUNGARIAN        Language
	ICELANDIC        Language
	INDONESIAN       Language
	IRISH            Language
	ITALIAN          Language
	JAPANESE         Language
	JAVANESE         Language
	KANNADA          Language
	KAZAKH           Language
	KHMER            Language
	KOREAN           Language
	KURDISH          Language
	KYRGYZ           Language
	LAO              Language
	LATVIAN          Language
	LITHUANIAN       Language
	MACEDONIAN       Language
	MALAY            Language
	MALAYALAM        Language
	MARATHI          Language
	MONGOLIAN        Language
	NEPALI           Language
	NORWEGIAN        Language
	ORIYA            Language
	PASHTO           Language
	PERSIAN          Language
	POLISH           Language
	PORTUGUESE       Language
	PUNJABI          Language
	ROMANIAN         Language
	RUSSIAN          Language
	SERBIAN          Language
	SINHALA          Language
	SLOVAK           Language
	SLOVENIAN        Language
	SOMALI           Language
	SPANISH          Language
	SUNDANESE        Language
	SWAHILI          Language
	SWEDISH          Language
	TAGALOG          Language
	TAJIK            Language
	TAMIL            Language
	TATAR            Language
	TELUGU           Language
	THAI             Language
	TIBETAN          Language
	TURKISH          Language
	TURKMEN          Language
	UKRAINIAN        Language
	URDU             Language
	UZBEK            Language
	VIETNAMESE       Language
	WU_CHINESE       Language
	XHOSA            Language
	YIDDISH          Language
	YORUBA           Language
	ZULU             Language
}{
	AFRIKAANS:        AFRIKAANS,
	ALBANIAN:         ALBANIAN,
	AMHARIC:          AMHARIC,
	ARABIC:           ARABIC,
	ARMENIAN:         ARMENIAN,
	ASSAMESE:         ASSAMESE,
	AZERBAIJANI:      AZERBAIJANI,
	BENGALI:          BENGALI,
	BOSNIAN:          BOSNIAN,
	BULGARIAN:        BULGARIAN,
	BURMESE:          BURMESE,
	CATALAN:          CATALAN,
	CHINESE_MANDARIN: CHINESE_MANDARIN,
	CROATIAN:         CROATIAN,
	CZECH:            CZECH,
	DANISH:           DANISH,
	DUTCH:            DUTCH,
	ENGLISH:          ENGLISH,
	ESTONIAN:         ESTONIAN,
	FINNISH:          FINNISH,
	FRENCH:           FRENCH,
	GEORGIAN:         GEORGIAN,
	GERMAN:           GERMAN,
	GREEK:            GREEK,
	GUJARATI:         GUJARATI,
	HEBREW:           HEBREW,
	HINDI:            HINDI,
	HUNGARIAN:        HUNGARIAN,
	ICELANDIC:        ICELANDIC,
	INDONESIAN:       INDONESIAN,
	IRISH:            IRISH,
	ITALIAN:          ITALIAN,
	JAPANESE:         JAPANESE,
	JAVANESE:         JAVANESE,
	KANNADA:          KANNADA,
	KAZAKH:           KAZAKH,
	KHMER:            KHMER,
	KOREAN:           KOREAN,
	KURDISH:          KURDISH,
	KYRGYZ:           KYRGYZ,
	LAO:              LAO,
	LATVIAN:          LATVIAN,
	LITHUANIAN:       LITHUANIAN,
	MACEDONIAN:       MACEDONIAN,
	MALAY:            MALAY,
	MALAYALAM:        MALAYALAM,
	MARATHI:          MARATHI,
	MONGOLIAN:        MONGOLIAN,
	NEPALI:           NEPALI,
	NORWEGIAN:        NORWEGIAN,
	ORIYA:            ORIYA,
	PASHTO:           PASHTO,
	PERSIAN:          PERSIAN,
	POLISH:           POLISH,
	PORTUGUESE:       PORTUGUESE,
	PUNJABI:          PUNJABI,
	ROMANIAN:         ROMANIAN,
	RUSSIAN:          RUSSIAN,
	SERBIAN:          SERBIAN,
	SINHALA:          SINHALA,
	SLOVAK:           SLOVAK,
	SLOVENIAN:        SLOVENIAN,
	SOMALI:           SOMALI,
	SPANISH:          SPANISH,
	SUNDANESE:        SUNDANESE,
	SWAHILI:          SWAHILI,
	SWEDISH:          SWEDISH,
	TAGALOG:          TAGALOG,
	TAJIK:            TAJIK,
	TAMIL:            TAMIL,
	TATAR:            TATAR,
	TELUGU:           TELUGU,
	THAI:             THAI,
	TIBETAN:          TIBETAN,
	TURKISH:          TURKISH,
	TURKMEN:          TURKMEN,
	UKRAINIAN:        UKRAINIAN,
	URDU:             URDU,
	UZBEK:            UZBEK,
	VIETNAMESE:       VIETNAMESE,
	WU_CHINESE:       WU_CHINESE,
	XHOSA:            XHOSA,
	YIDDISH:          YIDDISH,
	YORUBA:           YORUBA,
	ZULU:             ZULU,
}

var Occupations = struct {
	SOFTWARE_ENGINEER   Occupation
	HARDWARE_ENGINEER   Occupation
	ELECTRICAL_ENGINEER Occupation
	MECHANICAL_ENGINEER Occupation
	CIVIL_ENGINEER      Occupation
	BIOMEDICAL_ENGINEER Occupation
	DOCTOR              Occupation
	NURSE               Occupation
	TEACHER             Occupation
	PROFESSOR           Occupation
	ARTIST              Occupation
	MUSICIAN            Occupation
	WRITER              Occupation
	ACCOUNTANT          Occupation
	LAWYER              Occupation
	POLICE_OFFICER      Occupation
	FIREFIGHTER         Occupation
	CHEF                Occupation
	ARCHITECT           Occupation
	SCIENTIST           Occupation
	STUDENT             Occupation
	RETIREE             Occupation
	ENTREPRENEUR        Occupation
	ATHLETE             Occupation
	JOURNALIST          Occupation
	DESIGNER            Occupation
	PHARMACIST          Occupation
	SOCIAL_WORKER       Occupation
	OTHER_OCCUPATION    Occupation
}{
	SOFTWARE_ENGINEER:   SOFTWARE_ENGINEER,
	HARDWARE_ENGINEER:   HARDWARE_ENGINEER,
	ELECTRICAL_ENGINEER: ELECTRICAL_ENGINEER,
	MECHANICAL_ENGINEER: MECHANICAL_ENGINEER,
	CIVIL_ENGINEER:      CIVIL_ENGINEER,
	BIOMEDICAL_ENGINEER: BIOMEDICAL_ENGINEER,
	DOCTOR:              DOCTOR,
	NURSE:               NURSE,
	TEACHER:             TEACHER,
	PROFESSOR:           PROFESSOR,
	ARTIST:              ARTIST,
	MUSICIAN:            MUSICIAN,
	WRITER:              WRITER,
	ACCOUNTANT:          ACCOUNTANT,
	LAWYER:              LAWYER,
	POLICE_OFFICER:      POLICE_OFFICER,
	FIREFIGHTER:         FIREFIGHTER,
	CHEF:                CHEF,
	ARCHITECT:           ARCHITECT,
	SCIENTIST:           SCIENTIST,
	STUDENT:             STUDENT,
	RETIREE:             RETIREE,
	ENTREPRENEUR:        ENTREPRENEUR,
	ATHLETE:             ATHLETE,
	JOURNALIST:          JOURNALIST,
	DESIGNER:            DESIGNER,
	PHARMACIST:          PHARMACIST,
	SOCIAL_WORKER:       SOCIAL_WORKER,
	OTHER_OCCUPATION:    OTHER_OCCUPATION,
}

var Interests = struct {
	ANIMALS                 Interest
	ART                     Interest
	BEACH                   Interest
	BOARD_GAMES             Interest
	BOOKS                   Interest
	COOKING                 Interest
	CRAFTS                  Interest
	CRYPTO                  Interest
	DANCING                 Interest
	DECENTRALIZATION        Interest
	DRAWING                 Interest
	ENTREPRENEURSHIP        Interest
	EXERCISE                Interest
	FASHION                 Interest
	FITNESS                 Interest
	FOOD                    Interest
	GAMING                  Interest
	GARDENING               Interest
	HEALTH_WELLNESS         Interest
	HIKING                  Interest
	HOME_DECOR              Interest
	LANGUAGES               Interest
	MOVIES                  Interest
	MUSIC                   Interest
	NATURE                  Interest
	PAINTING                Interest
	PHOTOGRAPHY             Interest
	POETRY                  Interest
	READING                 Interest
	RUNNING                 Interest
	SCIENCE                 Interest
	SELF_IMPROVEMENT        Interest
	SHOPPING                Interest
	SPORTS                  Interest
	TECHNOLOGY              Interest
	TRAVEL                  Interest
	VOLUNTEERING            Interest
	WRITING                 Interest
	ASTROLOGY               Interest
	ASTRONOMY               Interest
	COFFEE                  Interest
	TEA                     Interest
	HISTORY                 Interest
	PHILOSOPHY              Interest
	CINEMA                  Interest
	THEATER                 Interest
	MUSIC_PRODUCTION        Interest
	DANCE                   Interest
	FITNESS_CLASSES         Interest
	YOGA                    Interest
	MEDITATION              Interest
	PODCASTS                Interest
	COMICS                  Interest
	VIDEO_GAMES             Interest
	CARD_GAMES              Interest
	POLITICS                Interest
	ENVIRONMENT             Interest
	TRADING                 Interest
	INVESTING               Interest
	FINANCE                 Interest
	ARTIFICIAL_INTELLIGENCE Interest
	MACHINE_LEARNING        Interest
	DATA_SCIENCE            Interest
	CYBERSECURITY           Interest
	WEB_DEVELOPMENT         Interest
	MOBILE_DEVELOPMENT      Interest
	BLOCKCHAIN              Interest
	DEFI                    Interest
	NFTS                    Interest
	DAPPS                   Interest
	CRYPTO_TRADING          Interest
	MINING                  Interest
	WEB3                    Interest
	CRYPTO_INVESTING        Interest
	BLOCKCHAIN_DEVELOPMENT  Interest
	GENEALOGY               Interest
	ANIME                   Interest
	MANGA                   Interest
	COSPLAY                 Interest
	URBAN_EXPLORATION       Interest
	SURFING                 Interest
	SKATEBOARDING           Interest
	SNOWBOARDING            Interest
	SKIING                  Interest
	CAMPING                 Interest
	BACKPACKING             Interest
	SURVIVALISM             Interest
	FORAGING                Interest
	ARTISANAL_CRAFTS        Interest
	CALLIGRAPHY             Interest
	GLASSBLOWING            Interest
	POTTERY                 Interest
	KNITTING                Interest
	CROCHETING              Interest
	EMBROIDERY              Interest
	SEWING                  Interest
	WOODWORKING             Interest
	METALWORKING            Interest
	LEATHERWORKING          Interest
	BEEKEEPING              Interest
	HOMEBREWING             Interest
	WINE_MAKING             Interest
	SPIRITS_DISTILLING      Interest
	MIXOLOGY                Interest
	COCKTAILS               Interest
	BEER                    Interest
	WINE                    Interest
	WHISKY                  Interest
	RUM                     Interest
	VODKA                   Interest
	GIN                     Interest
	TEQUILA                 Interest
	BRANDY                  Interest
	CIDER                   Interest
	MEAD                    Interest
	SODA                    Interest
	JUICE                   Interest
}{
	ANIMALS:                 ANIMALS,
	ART:                     ART,
	BEACH:                   BEACH,
	BOARD_GAMES:             BOARD_GAMES,
	BOOKS:                   BOOKS,
	COOKING:                 COOKING,
	CRAFTS:                  CRAFTS,
	CRYPTO:                  CRYPTO,
	DANCING:                 DANCING,
	DECENTRALIZATION:        DECENTRALIZATION,
	DRAWING:                 DRAWING,
	ENTREPRENEURSHIP:        ENTREPRENEURSHIP,
	EXERCISE:                EXERCISE,
	FASHION:                 FASHION,
	FITNESS:                 FITNESS,
	FOOD:                    FOOD,
	GAMING:                  GAMING,
	GARDENING:               GARDENING,
	HEALTH_WELLNESS:         HEALTH_WELLNESS,
	HIKING:                  HIKING,
	HOME_DECOR:              HOME_DECOR,
	LANGUAGES:               LANGUAGES,
	MOVIES:                  MOVIES,
	MUSIC:                   MUSIC,
	NATURE:                  NATURE,
	PAINTING:                PAINTING,
	PHOTOGRAPHY:             PHOTOGRAPHY,
	POETRY:                  POETRY,
	READING:                 READING,
	RUNNING:                 RUNNING,
	SCIENCE:                 SCIENCE,
	SELF_IMPROVEMENT:        SELF_IMPROVEMENT,
	SHOPPING:                SHOPPING,
	SPORTS:                  SPORTS,
	TECHNOLOGY:              TECHNOLOGY,
	TRAVEL:                  TRAVEL,
	VOLUNTEERING:            VOLUNTEERING,
	WRITING:                 WRITING,
	ASTROLOGY:               ASTROLOGY,
	ASTRONOMY:               ASTRONOMY,
	COFFEE:                  COFFEE,
	TEA:                     TEA,
	HISTORY:                 HISTORY,
	PHILOSOPHY:              PHILOSOPHY,
	CINEMA:                  CINEMA,
	THEATER:                 THEATER,
	MUSIC_PRODUCTION:        MUSIC_PRODUCTION,
	DANCE:                   DANCE,
	FITNESS_CLASSES:         FITNESS_CLASSES,
	YOGA:                    YOGA,
	MEDITATION:              MEDITATION,
	PODCASTS:                PODCASTS,
	COMICS:                  COMICS,
	VIDEO_GAMES:             VIDEO_GAMES,
	CARD_GAMES:              CARD_GAMES,
	POLITICS:                POLITICS,
	ENVIRONMENT:             ENVIRONMENT,
	TRADING:                 TRADING,
	INVESTING:               INVESTING,
	FINANCE:                 FINANCE,
	ARTIFICIAL_INTELLIGENCE: ARTIFICIAL_INTELLIGENCE,
	MACHINE_LEARNING:        MACHINE_LEARNING,
	DATA_SCIENCE:            DATA_SCIENCE,
	CYBERSECURITY:           CYBERSECURITY,
	WEB_DEVELOPMENT:         WEB_DEVELOPMENT,
	MOBILE_DEVELOPMENT:      MOBILE_DEVELOPMENT,
	BLOCKCHAIN:              BLOCKCHAIN,
	DEFI:                    DEFI,
	NFTS:                    NFTS,
	DAPPS:                   DAPPS,
	CRYPTO_TRADING:          CRYPTO_TRADING,
	MINING:                  MINING,
	WEB3:                    WEB3,
	CRYPTO_INVESTING:        CRYPTO_INVESTING,
	BLOCKCHAIN_DEVELOPMENT:  BLOCKCHAIN_DEVELOPMENT,
	GENEALOGY:               GENEALOGY,
	ANIME:                   ANIME,
	MANGA:                   MANGA,
	COSPLAY:                 COSPLAY,
	URBAN_EXPLORATION:       URBAN_EXPLORATION,
	SURFING:                 SURFING,
	SKATEBOARDING:           SKATEBOARDING,
	SNOWBOARDING:            SNOWBOARDING,
	SKIING:                  SKIING,
	CAMPING:                 CAMPING,
	BACKPACKING:             BACKPACKING,
	SURVIVALISM:             SURVIVALISM,
	FORAGING:                FORAGING,
	ARTISANAL_CRAFTS:        ARTISANAL_CRAFTS,
	CALLIGRAPHY:             CALLIGRAPHY,
	GLASSBLOWING:            GLASSBLOWING,
	POTTERY:                 POTTERY,
	KNITTING:                KNITTING,
	CROCHETING:              CROCHETING,
	EMBROIDERY:              EMBROIDERY,
	SEWING:                  SEWING,
	WOODWORKING:             WOODWORKING,
	METALWORKING:            METALWORKING,
	LEATHERWORKING:          LEATHERWORKING,
	BEEKEEPING:              BEEKEEPING,
	HOMEBREWING:             HOMEBREWING,
	WINE_MAKING:             WINE_MAKING,
	SPIRITS_DISTILLING:      SPIRITS_DISTILLING,
	MIXOLOGY:                MIXOLOGY,
	COCKTAILS:               COCKTAILS,
	BEER:                    BEER,
	WINE:                    WINE,
	WHISKY:                  WHISKY,
	RUM:                     RUM,
	VODKA:                   VODKA,
	GIN:                     GIN,
	TEQUILA:                 TEQUILA,
	BRANDY:                  BRANDY,
	CIDER:                   CIDER,
	MEAD:                    MEAD,
	SODA:                    SODA,
	JUICE:                   JUICE,
}

var SocialMediaLinks = struct {
	GITHUB_LINK   SocialMediaLink
	FACEBOOK_LINK SocialMediaLink
	TWITTER       SocialMediaLink
	INSTAGRAM     SocialMediaLink
	LINKEDIN      SocialMediaLink
	PINTEREST     SocialMediaLink
	TIKTOK        SocialMediaLink
	REDDIT        SocialMediaLink
	DISCORD       SocialMediaLink
	TELEGRAM      SocialMediaLink
	YOUTUBE       SocialMediaLink
	SLACK         SocialMediaLink
	TWITCH        SocialMediaLink
	SPOTIFY       SocialMediaLink
	SOUNDCLOUD    SocialMediaLink
}{
	GITHUB_LINK:   GITHUB_LINK,
	FACEBOOK_LINK: FACEBOOK_LINK,
	TWITTER:       TWITTER,
	INSTAGRAM:     INSTAGRAM,
	LINKEDIN:      LINKEDIN,
	PINTEREST:     PINTEREST,
	TIKTOK:        TIKTOK,
	REDDIT:        REDDIT,
	DISCORD:       DISCORD,
	TELEGRAM:      TELEGRAM,
	YOUTUBE:       YOUTUBE,
	SLACK:         SLACK,
	TWITCH:        TWITCH,
	SPOTIFY:       SPOTIFY,
	SOUNDCLOUD:    SOUNDCLOUD,
}

// class DateFormat(Enum):
//     """Applications Permitted Date Formats."""

//     SHORT: "%y/%m"  # Format 2: "24/03"
//     LONG: "%d %B %Y %H:%M:%S"  # Format 1: "14 March 2024 20:05:12"
//     SLASH = "%Y/%m/%d %H:%M:%S"  # Format 2: "2024/03/14 20:05:12"
//     HYPHEN = "%Y-%m-%d %H:%M:%S"  # Format 3: "2024-03-14 20:05:12"

// class Regex(Enum):
//     """Holds Regex Constants That are Applicable to the Application."""

//     EMAIL: Pattern = regex_compile(
//         r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-_]+\.[a-zA-Z]{1,3}\.?[a-zA-Z]{2,3}$"
//     )
//     PASSWORD: Pattern = regex_compile(
//         r"^(?=.*[a-zA-Z])(?=.*\d)(?=.*[!@#$%^&*()-_+=]).{8,}$"
//     )
//     NAME = regex_compile(r"^[a-zA-Z]{1,30}$")
//     USERNAME = regex_compile(r"^[a-zA-Z][a-zA-Z0-9\s\-_@#]{8,30}$")
//     MOBILE_NUMBER = regex_compile(r"^\+\d{1,3}\d{3,14}$")
//     DESCRIPTION = regex_compile(r"^[a-zA-Z][a-zA-Z0-9\s\-,._]{8,125}$")
//     BIOGRAPHY = regex_compile(r"^(?!\s+$).{8,250}$")
//     PIN = regex_compile(r"^\d{6}$")
//     CVV = regex_compile(r"^\d+$")

// class CardType(Enum):
//     """Enumeration of Card Types."""

//     CHEQUE = "cheque", "1991"
//     SAVINGS = "savings", "1992"
//     CREDIT = "credit", "1993"
